sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: dal_test
  username: dal_test_user
  password: not_very_secure
  encoding: utf8

before_script:
  - composer install -n ; fi

script:
  - phpunit
